feat: user mailing list
dailydotdev/daily-api pull request #1019
Opened 2022-08-22 05:56 UTC by sshanzel

Migrated the workers from the gateway.

2022-08-22 05:59 UTC, rebelchris approved these changes
Nice work on this 🙏

2022-08-22 06:04 UTC, sshanzel commented on src/common/mailing.ts
> +type HttpMethod =
The type-safety of sendgrid shouts when sending the parameters without casting the method to this type.

2022-08-22 06:41 UTC, idoshamun commented on .infra/workers.ts
> +  },
I think these subs already exist in the gateway. Am I right?
If so, Pulumi will not be able to create them. We might need to do some manual work here. Let's think about it later

2022-08-22 06:43 UTC, idoshamun requested changes
I think we have to approach this PR a bit differently.
If we still rely on the events we receive from the gateway, we still rely on the gateway itself.
So I suggest publishing new events based on changes in the users table of the API and then update the mailing list accordingly.
What do you think? cc @rebelchris

2022-08-22 09:34 UTC, sshanzel commented
> I think we have to approach this PR a bit differently.
If we still rely on the events we receive from the gateway, we still rely on the gateway itself.
So I suggest publishing new events based on changes in the user's table of the API and then update the mailing list accordingly.

I actually initially thought of publishing an event here in the API (but was missing in this PR), but now that we have kept the user change event in the gateway, and kept the changes minimal, we should not need an additional worker for the moment. WDYT?

2022-08-22 09:35 UTC, idoshamun commented
Let's wait for the planning meeting and we decide :)

2022-08-30 12:58 UTC, rebelchris approved these changes

2022-08-30 12:58 UTC, rebelchris commented on .infra/workers.ts
> +    topic: 'user-updated',
This should be user-deleted topic

2022-08-30 12:59 UTC, merged