fix: prevent slack messages for share posts
dailydotdev/daily-api pull request #1153
Opened 2023-01-27 10:37 UTC by rebelchris

Prevent slack messages for share posts.

@idoshamun Perhaps we need to rather introduce a `private` flag on posts. (inherited from their source)
Based on that flag we can then prevent certain actions rather. 

I think that might be more future proof.

WT-982 #done

2023-01-27 13:17 UTC, el approved these changes

2023-01-29 09:27 UTC, idoshamun requested changes
This looks great! The only thing missing is a CDC that updates posts privacy when the source's privacy changes

2023-01-29 09:29 UTC, rebelchris commented
@idoshamun Was wondering about that, how can that happen?
Didn't see any events for changing the privacy (something you do in DB only?)

2023-01-29 09:33 UTC, idoshamun commented
@rebelchris in the future this will probably be supported and I'm afraid to forget about this mechanism

2023-01-30 13:26 UTC, rebelchris commented
@idoshamun I added the source CDC change

2023-01-30 15:05 UTC, idoshamun commented on .infra/workers.ts
> +    subscription: 'source-privacy-updated-api',
Fix according to the new convention
```suggestion
    subscription: 'api.source-privacy-updated',
```

2023-01-30 15:07 UTC, idoshamun commented on src/common/pubsub.ts
> +  publishEvent(log, sourcePrivacyUpdatedTopic, { sourceId, privacy });
Should we consider publishing the complete source object?

2023-01-30 15:08 UTC, idoshamun commented on src/workers/sourcePrivacyUpdated.ts
> +      }
This needs to be removed. Otherwise, it may be out of sync

2023-01-30 15:10 UTC, idoshamun reviewed
Some minor changes

2023-01-31 16:18 UTC, idoshamun approved these changes

2023-01-31 16:21 UTC, merged