refactor: unnecessary live post notification
dailydotdev/daily-api pull request #1246
Opened 2023-04-24 14:08 UTC by sshanzel

**Blocked**: until [preview PR in FE](https://github.com/dailydotdev/apps/pull/1744) is merged.

Sync external link submission post-release removal of the post_live notification.

2023-04-24 14:16 UTC, rebelchris requested changes
This looks good.
Just a suggestion for full clean up

2023-04-24 14:33 UTC, sshanzel commented on src/workers/notifications/postAdded.ts
> -              type: 'squad_post_live',
I tried searching the codebase but I don't seem to see any additional trigger points. Do you remember the specific place/use case?

2023-04-24 15:06 UTC, rebelchris commented on src/workers/notifications/postAdded.ts
> -              type: 'squad_post_live',
Its not trigger, mainly the actual notifications related to it.

2023-04-24 15:19 UTC, sshanzel commented on src/workers/notifications/postAdded.ts
> -              type: 'squad_post_live',
Ah, you mean removing it on the notifications generator? Thought of it too but refrained from doing so, but if we don't see any use for it in the future, then I'd be glad to clean those up 🚀

2023-04-25 06:38 UTC, rebelchris commented on src/workers/notifications/postAdded.ts
> -              type: 'squad_post_live',
Personally don't see any use as it won't ever be triggered.
We can always reintroduce from the history if need be.

2023-04-25 11:47 UTC, rebelchris approved these changes
Nice work :)

2023-04-25 11:51 UTC, idoshamun approved these changes

2023-04-25 15:36 UTC, merged