feat: setting welcomePost as showOnFeed as false by default
dailydotdev/daily-api pull request #1360
Opened 2023-07-20 08:51 UTC by TomDowling

Setting the showOnFeed flag as false by default for welcomePosts

2023-07-20 09:01 UTC, rebelchris requested changes
this is great, part of this ticket was also to retro fix existing squads (which will need a script probably)
Would you want to take that one on as well? (else let me know I can support on it)

2023-07-20 11:10 UTC, idoshamun commented
@rebelchris I think a simple migration can also be useful as a retro fix. Should be straightforward

2023-07-20 11:11 UTC, idoshamun commented on src/common/post.ts
> +      showOnFeed: false,
Currently `flags` is not used as a primary source so we should add `showOnFeed` as a main property of the object

2023-07-20 11:11 UTC, idoshamun requested changes
Please check my comment. Also we should update the tests I guess right?

2023-07-20 13:09 UTC, rebelchris commented
@idoshamun Added all comments and a new test case as we didn't explicitly test for it

2023-07-20 13:59 UTC, idoshamun commented on src/migration/1689854830946-WelcomeShowOnFeed.ts
> +      `UPDATE post SET flags = flags || '{"showOnFeed": false}' WHERE type = 'welcome'`,
We need to set `showOnFeed` itself as well here

2023-07-20 14:14 UTC, idoshamun commented on src/migration/1689854830946-WelcomeShowOnFeed.ts
> +      `UPDATE post SET flags = flags || '{"showOnFeed": false}' WHERE type = 'welcome'`,
I see it only in `down` the `up` wasn't changed

2023-07-20 14:25 UTC, rebelchris commented
@idoshamun rushing was a bad idea, fixed both now

2023-07-20 14:31 UTC, idoshamun approved these changes
Perfect!

2023-07-21 05:38 UTC, sshanzel approved these changes
Looks great!

2023-07-21 07:59 UTC, merged