feat: single search session query
dailydotdev/daily-api pull request #1392
Opened 2023-08-11 11:17 UTC by sshanzel

Fetch a single search session by session id from the session history list.

2023-08-11 14:16 UTC, rebelchris approved these changes
Looks good

2023-08-12 14:04 UTC, idoshamun approved these changes

2023-08-12 14:13 UTC, idoshamun commented on src/schema/search.ts
> +    completedAt: String!
Should be date

2023-08-12 14:13 UTC, idoshamun requested changes
Check my comment

2023-08-14 12:29 UTC, sshanzel commented on src/integrations/magni.ts
> +  if (!res.ok) throw new ValidationError(await res.text());
[After some discussion](https://dailydotdev.atlassian.net/wiki/spaces/HAN/pages/584286210/COM-90+AI+Search?focusedCommentId=596836378), the error that we would parse would only be coming from successful requests `res.ok = true`.

2023-08-15 06:26 UTC, idoshamun approved these changes

2023-08-17 09:15 UTC, merged