Fix typo
dailydotdev/daily-api pull request #1520
Opened 2023-10-31 16:11 UTC by VaibhavWakde52

2023-10-31 16:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/dailydotdev/daily-api?pullRequest=1520) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/dailydotdev/daily-api?pullRequest=1520) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/dailydotdev/daily-api?pullRequest=1520) it.</sub>

2023-10-31 16:19 UTC, rebelchris requested changes
Thanks for the fixes, just one note on a wrong change.

2023-10-31 16:19 UTC, rebelchris commented on README.md
> +- Typeform as a database layer
Its actually Typeorm 👍

2023-10-31 16:22 UTC, VaibhavWakde52 commented on README.md
> +- Typeform as a database layer
ohhh ,my bad , i will change it back

2023-10-31 16:42 UTC, rebelchris approved these changes
Thank you so much

2023-11-01 06:17 UTC, idoshamun approved these changes
Thank you very much!

2023-11-01 06:17 UTC, merged