feat: user post notification worker
dailydotdev/daily-api pull request #2280
Opened 2024-09-25 09:19 UTC by capJavert

AS-586

2024-09-25 13:01 UTC, omBratteng commented on src/workers/newNotificationV2Mail.ts
> +      con.getRepository(NotificationAvatarV2).findOneOrFail({
one is `await`, one is not?

2024-09-25 13:02 UTC, omBratteng approved these changes
LGTM, just one minor comment

2024-09-25 13:08 UTC, rebelchris requested changes
Blocking on template // todo

2024-09-25 13:08 UTC, rebelchris commented on src/workers/newNotificationV2Mail.ts
> +  user_post_added: 'test',
Just blocking for now

2024-09-25 13:08 UTC, rebelchris commented on src/workers/newNotificationV2Mail.ts
>    // TODO AS-534 add handler
TODO removal

2024-09-25 13:08 UTC, rebelchris commented on src/workers/notifications/postAddedUserNotification.ts
> +      const contentPreferenceQuery = con
Probably have to monitor if this query becomes heavy on PG

2024-09-26 09:06 UTC, capJavert commented on src/workers/newNotificationV2Mail.ts
> +  user_post_added: 'test',
sorted

2024-09-26 09:09 UTC, rebelchris approved these changes

2024-09-26 09:22 UTC, merged