feat: upvoted by queries for both posts and comments
dailydotdev/daily-api pull request #733
Opened 2021-09-21 16:20 UTC by sshanzel

- [x] API for Post's Upvote(s)
- [x] API for Comment's Upvote(s)

DD-30

2021-09-22 12:45 UTC, idoshamun commented on src/common/upvoteGenerator.ts
> +  IBaseUpvote,
```suggestion
 { createdAt: Date },
```

2021-09-22 12:45 UTC, idoshamun requested changes
I don't like the fact that we require entities to inherit from another class. It might mess with reflection things that TypeORM does. So I think we should revert back to a more explicit form of entities declare user and createdAt. But what we can do to achieve the same thing with the page generator is just to force the generic argument to have the `createdAt` field.
I added an inline suggestion, please make sure it works.
Other than that it looks fabulous!

**A friendly reminder to add tests**

2021-09-23 03:29 UTC, sshanzel commented
This should be now ready for review. I just revised the test cases I made to make the snapshot contain the some actual data to have better integrity. I am starting to love to write unit tests now 😆

2021-09-23 05:48 UTC, idoshamun requested changes
I think it's better to add one more item in the tests so we can check that it returns a list ordered by `createdAt`. What do you think?

2021-09-23 05:52 UTC, sshanzel commented
True, we should do that, since we specifically want it be ordered in a descending manner. I'll write another one for this. Thanks for the thought!

2021-09-23 05:53 UTC, idoshamun commented
@sshanzel you can use the same test, I think

2021-09-23 07:18 UTC, sshanzel commented
I am starting to love writing unit-tests! Lol. I have now applied an item that will determine the order of the result.

2021-09-23 07:50 UTC, idoshamun requested changes
Tests are now failing because you saved to the snapshot dates that are based on the current time. My recommendation is to use fixed dates. This will make sure the snapshot data is persistent and the tests will pass. After this, we can merge! 🚀

2021-09-23 08:06 UTC, sshanzel commented
Weird. Earlier I have tried a constant date but the dates kept on mismatching, though it was like a day difference on the post's test but not on the comment's test 🤪  Strange that it is working now. Lol. Pushing in a few seconds..

2021-09-23 08:56 UTC, idoshamun approved these changes
Woohoo! 🚀

2021-09-23 09:00 UTC, merged

2021-09-23 09:03 UTC, sshanzel commented
Oh yeah! 🎸🤘 Thank you so much! 🙏