feat: added comment to report reasons
dailydotdev/daily-api pull request #778
Opened 2021-11-02 06:20 UTC by rebelchris

When a user reports a post, they can now provide a comment with their chosen reason.

2021-11-02 06:24 UTC, idoshamun requested changes
Please also add the new comment field to Slack's notification.

2021-11-02 06:24 UTC, idoshamun commented on __tests__/posts.ts
>  describe('mutation reportPost', () => {
Can you add a test that doesn't send a comment so we'll check for backward compatibility?

2021-11-02 06:24 UTC, idoshamun commented on src/entity/PostReport.ts
> +  comment: string;
```suggestion
  @Column({ type: 'text', nullable: true })
  comment?: string;
```

2021-11-02 06:42 UTC, rebelchris commented
@idoshamun Thanks for spotting the slack webhook.
Also added test for empty comments.

2021-11-02 06:46 UTC, idoshamun requested changes
I think you forgot to regenerate the migration

2021-11-02 07:06 UTC, sshanzel requested changes
Just this one super tiny thing with linting.

2021-11-02 07:12 UTC, rebelchris commented on src/schema/posts.ts
> +              comment: comment,
Oh nice spot! Thanks Lee 🎉

2021-11-02 07:21 UTC, sshanzel approved these changes
Woohoo! LGTM! 🚢

2021-11-03 10:02 UTC, rebelchris commented
@idoshamun Would you mind checking this one as well.

2021-11-03 10:13 UTC, idoshamun approved these changes
LGTM!

2021-11-03 11:02 UTC, merged