WIP: feat: sidebar toggle mode
dailydotdev/daily-api pull request #812
Opened 2021-12-02 09:46 UTC by rebelchris

The WIP for the API side of things.
Related to frontend changes: https://github.com/dailydotdev/apps/pull/721

This is only a WIP and need to receive test

2021-12-02 10:24 UTC, sshanzel requested changes
Just this one thing and update the snapshots then this should be good to go 🚀

2021-12-02 10:24 UTC, sshanzel commented on src/schema/settings.ts
> +    openSidebar: Boolean!
This shouldn't be required just like the others.

```suggestion
    openSidebar: Boolean
```

2021-12-06 06:40 UTC, idoshamun approved these changes
Looking good!
I love the fact that we don't have to change anything on the query once we introduce a new column.

2021-12-07 06:19 UTC, sshanzel approved these changes
LGTM! 🚢

2021-12-07 06:19 UTC, merged