feat: :sparkles: Added a new hook to post to slack on every comment
dailydotdev/daily-api pull request #848
Opened 2022-01-07 14:17 UTC by rebelchris

I've added a new slack hook to act on every comment.
For now this will post in the same channel but with out avo green color.

I haven't been able to test end-to-end because I don't know the new webhook url.

The test and local CDC all go well though.

DD-326 #done

2022-01-08 10:35 UTC, idoshamun requested changes
The best practice here is not to use CDC but rather create a new subscription that only sends the slack notification. The reason is that we want to optimally run exactly one side-effect for every message we handle. Otherwise, the retry mechanism can be a mess. Imagine you sent the slack notification here and then for some reason something failed down the line. It will cause Pub/Sub to send again the same message and basically flood our Slack channel. This is something called distributed transaction in distributed systems. The best way to handle it, is to bypass the need for such transactions by introducing multiple subscriptions that listens to the same domain event. In our case the domain event is pos commented. The CDC topic is not a domain event but rather something technical that we use to generate domain events out of it.

2022-01-08 13:31 UTC, rebelchris commented
@idoshamun Thanks, that makes sense, I'll refactor to it'w own subscription.
I did see the report webhook runs over the CDC, that's still fine then?

2022-01-10 09:26 UTC, rebelchris commented
@idoshamun Refactored to two new subscriptions one for the commentComment and one for postComment.
It seems you cannot re-use the same subscription on the same topic, hence I made two.

Looking forward to hearing what you think.

2022-01-10 14:16 UTC, idoshamun requested changes
Other than naming concerns I'm speechless.
Way to go :)

2022-01-10 14:16 UTC, idoshamun commented on infra/workers.ts
> +    topic: 'post-commented',
👀 

```suggestion
    topic: 'comment-commented',
```

2022-01-10 14:16 UTC, idoshamun commented on infra/workers.ts
> +    subscription: 'comment-comment-slack-message',
```suggestion
    subscription: 'comment-commented-slack-message',
```

2022-01-10 14:16 UTC, idoshamun commented on infra/workers.ts
> +    subscription: 'post-comment-slack-message',
```suggestion
    subscription: 'post-commented-slack-message',
```

2022-01-10 14:16 UTC, idoshamun commented on src/workers/commentCommentSlackMessage.ts
> +  subscription: 'comment-comment-slack-message',
```suggestion
  subscription: 'comment-commented-slack-message',
```

2022-01-10 14:16 UTC, idoshamun commented on src/workers/postCommentSlackMessage.ts
> +  subscription: 'post-comment-slack-message',
```suggestion
  subscription: 'post-commented-slack-message',
```

2022-01-14 16:26 UTC, idoshamun approved these changes
Looks great!

2022-01-16 08:54 UTC, sshanzel approved these changes
So cool to see we can now confidently say the CDC pipeline works. Well done! 🚢

2022-01-17 06:57 UTC, merged