fix: my feed column default value is null
dailydotdev/daily-api pull request #849
Opened 2022-01-11 12:50 UTC by sshanzel

The 'created' value should explicitly be defined when the user has created his own feed.

2022-01-11 13:20 UTC, idoshamun commented
This is a correct fix but I think we should also set the alert to created when a new feed is created for the first time. Actually it's pretty straight forward with CDC. We can listen to the feed table. What do you think?

2022-01-11 13:50 UTC, sshanzel commented
I totally agree that it must be updated. Have applied the necessary changes and tests to ensure workability 🚢

2022-01-11 16:03 UTC, idoshamun requested changes
Two comments about the tests other than that looks great!

2022-01-11 16:03 UTC, idoshamun commented on __tests__/workers/cdc.ts
> +  it('should notify on alerts created', async () => {
```suggestion
  it('should update alerts when feed is created', async () => {
```

2022-01-11 16:03 UTC, idoshamun commented on __tests__/workers/cdc.ts
> +    expect(mocked(updateAlerts).mock.calls[0]).toEqual(params);
Let's test that the DB indeed changed.
I usually mock the pubsub functions because there is no other way of testing it

2022-01-11 16:33 UTC, sshanzel commented on src/migration/1641904779220-AlertMyFeedDefaultValue.ts
> +export class AlertMyFeedDefaultValue1641904779220
Ah, yes. Having some issues with automatically making the migration, had to write it manually. My mistake.

2022-01-11 16:40 UTC, idoshamun commented on src/migration/1641904779220-AlertMyFeedDefaultValue.ts
> +export class AlertMyFeedDefaultValue1641904779220
Don't do it next time unless you really need to. If you have problem with generating automatically, let me know and I can help

2022-01-11 16:50 UTC, sshanzel commented on src/migration/1641904779220-AlertMyFeedDefaultValue.ts
> +export class AlertMyFeedDefaultValue1641904779220
Cool. I will check further this concern once we finish our big experiment and reach out if I bumped a wall. Initially, I have only tried running `npm run db:migrate:reset` then tried making a new one. Will let you know about the updates.

2022-01-11 16:51 UTC, sshanzel commented
The tests have turned green! 🟢 

Thank you for the awesome review! 🚀

2022-01-12 07:20 UTC, idoshamun approved these changes
It's ready!!

2022-01-12 08:04 UTC, merged